steps:
  - name: 'gcr.io/springer-nature-analytics/custom/beam_python:v1-custom'
    args:
      - bash
      - -c
      - |
        apt-get update
        apt-get install -y git
        git clone https://github.com/sangameshwar-karanjkar/ci_cd_test.git

  - name: 'gcr.io/springer-nature-analytics/custom/beam_python:v1-custom'
    args:
      - bash
      - -c
      - |
        cd ci_cd_test
        python3 test_dataflow.py --experiment=use_runner_v2 --worker_harness_container_image=gcr.io/springer-nature-analytics/custom/beam_python:v1-custom
        
